# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef63a181e7cd2350cac39708932307100b7b8825ded92aede0a7b0f0665ed1199c55336eceee3fa05c933c060ac150a25e78150bfcd7ffe50e31c4e957103047

test:
  secret_key_base: a07a803729aca8aa352e502c860c0b82392a3a8a8d5bbdc5fa98d57cfeac83ec6be10a0cf16a955447c18b9496667dc676837682bf181cd8d1ce730596f4cbc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
